version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "master.007,01"
      POSTGRES_DB: "POC"
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    networks:
      - backend
  teste-ready-run:
    build: .
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__POSTGRESCONNECTION: 'Server=postgres;Port=5432;User Id=postgres;Password=master.007,01;Database=POC;Pooling=true;'
      ASPNETCORE_ENVIRONMENT: 'Development'
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend: